### ISSUE TITLE
Linter issue

### ISSUE THREAD

**Issue by graciemcguire** [learn-co-curriculum/phase-0-completing-assignments#16]
### Canvas Link

https://learning.flatironschool.com/courses/3280/assignments/73666?module_item_id=142646

### Concern

```
MD013/line-length: Line length [Expected: 80; Actual: 122]
MD013/line-length: Line length [Expected: 80; Actual: 122]
MD013/line-length: Line length [Expected: 80; Actual: 101]
```

**Comment by ihollander** [comment]
These linting warning are for HTML elements that we need to use in the Markdown for certain custom elements (like iframes for embedded videos), so we can ignore these.
