### ISSUE TITLE
Fork button does not work

### ISSUE THREAD

**Issue by FranciscoNav** [learn-co-curriculum/phase-0-completing-assignments#2]
When I click the fork button it takes me back to here https://learn.co/tracks/online-software-engineering-ft-first-mile?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=426413333dc14f95ea637ced1b1fe75d75c3d287d3a25d33

**Comment by maxwellbenton** [comment]
Hey @FranciscoNav! 

Thank you for providing this feedback. This issue should be resolved. If you are still having issues, please feel free to open a new issue or reach out in the #js-prework-support Slack channel to get direct support.
