### ISSUE TITLE
A Quick Note on Organizing Work on Your Machine

### ISSUE THREAD

**Issue by kdcamzn** [learn-co-curriculum/phase-0-completing-assignments#23]
Under this section it might be helpful to clarify that mkdir on phase 0 - 5 is...

mkdir phase0
mkdir phase-0
mkdir phase_0

When looking at the git clone phase-0 is used so my assumption is mkdir phase-0.

**Comment by AlveeM** [comment]
Hi @kdcamzn, thanks for submitting the issue. 

We've updated the relevant sections to clarify naming conventions. These videos ([Mac](https://www.youtube.com/embed/_zeNHyW9gvw) or [WSL](https://www.youtube.com/embed/EwLe9M4xZlk) might be helpful for you too.

Thanks again for submitting the issue and helping us clarify the curriculum! We really appreciate your help!
