### ISSUE TITLE
update from Development/prework to Development/code/prework

### ISSUE THREAD

**Issue by brigj1** [learn-co-curriculum/phase-0-completing-assignments#27]
### Canvas Link

https://learning.flatironschool.com/courses/5506/assignments/170648?module_item_id=371027

### Concern

Page currently says:
Whenever you are starting a new assignment, navigate back to your main prework folder (cd ~/Development/prework) before cloning...

### Suggested Changes

the previous exercise had us make the 'prework' folder in 'code' so change the target to 'Development/code/prework'?

**Comment by professor-ben** [comment]
Thanks for your attention to detail! This has now been fixed and pushed to master.

-Ben
