### ISSUE TITLE
Fork brings up Flatiron base Home Screen

### ISSUE THREAD

**Issue by megansqueen** [learn-co-curriculum/phase-0-completing-assignments#38]
### Canvas Link

https://learning.flatironschool.com/courses/6106/assignments/205397?module_item_id=470986

### Concern

I had to use the Octocat icon because the fork icon kept redirecting me to the base home screen.

**Comment by jlboba** [comment]
Hi there, thank you for raising this issue!

I'm having difficulty reproducing the issue, so I'm going to close it for now.  If this continues happening for other lessons as well, I would recommend using the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit)  feature in Canvas to connect with a Technical Coach on the Academic Success Team to see if they can help. 

If the error is unable to be fixed and appears to be an issue with the lessons themselves, please feel free to reopen this issue. Thank you!
