### ISSUE TITLE
Repo name mismatch 

### ISSUE THREAD

**Issue by LuckyT89** [learn-co-curriculum/phase-0-completing-assignments#4]
The name of this repository is "phase-0-completing-assignments" but after cloning it, the instructions say to enter the command `cd welcome-completing-assignments` but this does not work because that directory does not exist. The instructions seem like they should be changed to say `cd phase-0-completing-assignments` so that it matches.

**Comment by lizbur10** [comment]
Hi @LuckyT89 ! Thank you for reporting this issue. The master copy of the lesson does not contain this error. Can you please post a link to the lesson in Canvas for me?

Thanks! 💙

**Comment by LuckyT89** [comment]
No problem! Here is a link to the Canvas assignment: https://my.learn.co/courses/43/assignments/2271

**Comment by lizbur10** [comment]
Thanks again for posting this, @LuckyT89 ! The error has been fixed but it may not appear in Canvas right away.
