### ISSUE TITLE
4 WARN running npm install

### ISSUE THREAD

**Issue by Jblack017** [learn-co-curriculum/phase-0-completing-assignments#6]
![image](https://user-images.githubusercontent.com/79665787/109432407-3d12e280-79c8-11eb-9f12-493d86edd0f7.png)

**Comment by lizbur10** [comment]
Hi there! Deprecation warnings are common but generally don't cause any problems. As long as you are able to run the tests and complete the labs you can just ignore them.

Cheers 💙
