### ISSUE TITLE
re: organizing work on your machine section

### ISSUE THREAD

**Issue by LJ-000** [learn-co-curriculum/phase-0-completing-assignments#7]
This section should be on the same page as the video walkthrough for organizing the file system. Being out of order throws the lesson's flow off.

**Comment by MikeLens32** [comment]
How do I start it over I jumped the gun on starting and I'm currently a little confused.

**Comment by lizbur10** [comment]
Hi @MikeLens32 ! If you post a question on the js-prework-support Slack channel someone will help you with this 😄 There are instructors available 9am - 9pm ET, Monday through Friday.

Cheers!
